### ISSUE TITLE
description of included js files

### ISSUE THREAD

**Issue by Gauravdarkslayer** [arpanaditya/buildo-testing#3]
can you guys please add which js file is used for which task? add some comments below that included js.

    <script src="js/jquery-min.js"></script>
    <script src="js/tether.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/mixitup.min.js"></script>
    <script src="js/nivo-lightbox.js"></script>
    <script src="js/owl.carousel.min.js"></script>    
    <script src="js/jquery.stellar.min.js"></script>    
    <script src="js/jquery.nav.js"></script>    
    <script src="js/smooth-scroll.js"></script>    
    <script src="js/smooth-on-scroll.js"></script>    
    <script src="js/wow.js"></script>    
    <script src="js/menu.js"></script>
    <script src="js/jquery.vide.js"></script>
    <script src="js/jquery.counterup.min.js"></script>    
    <script src="js/jquery.magnific-popup.min.js"></script>    
    <script src="js/waypoints.min.js"></script>    
    <script src="js/form-validator.min.js"></script>
    <script src="js/contact-form-script.js"></script>     
    <script src="js/main.js"></script>

**Comment by arpanaditya** [comment]
@I-ArchanaDash look into the issue

**Comment by I-ArchanaDash** [comment]
> can you guys please add which js file is used for which task? add some comments below that included js.
> 
> ```
> <script src="js/jquery-min.js"></script>
> <script src="js/tether.min.js"></script>
> <script src="js/bootstrap.min.js"></script>
> <script src="js/classie.js"></script>
> <script src="js/mixitup.min.js"></script>
> <script src="js/nivo-lightbox.js"></script>
> <script src="js/owl.carousel.min.js"></script>    
> <script src="js/jquery.stellar.min.js"></script>    
> <script src="js/jquery.nav.js"></script>    
> <script src="js/smooth-scroll.js"></script>    
> <script src="js/smooth-on-scroll.js"></script>    
> <script src="js/wow.js"></script>    
> <script src="js/menu.js"></script>
> <script src="js/jquery.vide.js"></script>
> <script src="js/jquery.counterup.min.js"></script>    
> <script src="js/jquery.magnific-popup.min.js"></script>    
> <script src="js/waypoints.min.js"></script>    
> <script src="js/form-validator.min.js"></script>
> <script src="js/contact-form-script.js"></script>     
> <script src="js/main.js"></script>
> ```

**Comment by I-ArchanaDash** [comment]
Updated
